-- 1. TABLAS INDEPENDIENTES (Sin llaves foráneas)
CREATE TABLE USUARIO (
    id_usuario    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre        VARCHAR2(100) NOT NULL,
    apellido      VARCHAR2(100) NOT NULL,
    email         VARCHAR2(150) UNIQUE NOT NULL,
    contrasena    VARCHAR2(255) NOT NULL,
    tipo_usuario  VARCHAR2(20) NOT NULL,
    CONSTRAINT chk_tipo_usuario CHECK (tipo_usuario IN ('ADMINISTRADOR', 'CLIENTE'))
);

CREATE TABLE CURSO (
    id_curso     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre       VARCHAR2(100) NOT NULL,
    descripcion  CLOB,
    f_inicio     DATE,
    f_fin        DATE,
    precio       NUMBER(10, 2)
);

CREATE TABLE MATERIAL (
    id_material  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre       VARCHAR2(100) NOT NULL,
    descripcion  CLOB,
    precio       NUMBER(10, 2),
    stock        NUMBER DEFAULT 0
);

-- 2. TABLAS DEPENDIENTES (Con llaves foráneas)
CREATE TABLE ALUMNO (
    id_alumno        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dni              VARCHAR2(20) UNIQUE,
    nombre           VARCHAR2(100) NOT NULL,
    apellido         VARCHAR2(100) NOT NULL,
    f_nacimiento     DATE NOT NULL,
    nivel            VARCHAR2(50),
    id_usuario       NUMBER NOT NULL,
    CONSTRAINT fk_alumno_usuario FOREIGN KEY (id_usuario) REFERENCES USUARIO(id_usuario) ON DELETE CASCADE
);

CREATE TABLE CLASE (
    id_clase     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grado        VARCHAR2(50),
    duracion_min NUMBER,
    id_curso     NUMBER,
    CONSTRAINT fk_clase_curso FOREIGN KEY (id_curso) REFERENCES CURSO(id_curso)
);

CREATE TABLE INSCRIPCION (
    codigo           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    f_inscripcion    DATE DEFAULT SYSDATE,
    estado           VARCHAR2(50),
    id_usuario       NUMBER NOT NULL,
    id_curso         NUMBER NOT NULL,
    id_alumno        NUMBER NOT NULL,
    CONSTRAINT fk_ins_usuario FOREIGN KEY (id_usuario) REFERENCES USUARIO(id_usuario),
    CONSTRAINT fk_ins_curso   FOREIGN KEY (id_curso)   REFERENCES CURSO(id_curso),
    CONSTRAINT fk_ins_alumno  FOREIGN KEY (id_alumno)  REFERENCES ALUMNO(id_alumno)
);

CREATE TABLE FEDERACION (
    n_licencia           VARCHAR2(50) PRIMARY KEY,
    categoria            VARCHAR2(50),
    f_alta               DATE,
    f_renovacion         DATE,
    resultados_competic  CLOB,
    documentos           CLOB,
    observaciones        CLOB,
    id_alumno            NUMBER UNIQUE,
    CONSTRAINT fk_fed_alumno FOREIGN KEY (id_alumno) REFERENCES ALUMNO(id_alumno)
);

CREATE TABLE PAGOS (
    id_pago      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    f_pago       DATE DEFAULT SYSDATE,
    tipo         VARCHAR2(50),
    precio       NUMBER(10, 2),
    estado       VARCHAR2(50),
    id_usuario   NUMBER NOT NULL,
    id_material  NUMBER,
    CONSTRAINT fk_pago_usuario  FOREIGN KEY (id_usuario)  REFERENCES USUARIO(id_usuario),
    CONSTRAINT fk_pago_material FOREIGN KEY (id_material) REFERENCES MATERIAL(id_material)
);